### ISSUE TITLE
Don't override vim keybinds

### ISSUE THREAD

**Issue by musjj** [mikesmithgh/kitty-scrollback.nvim#12]
Is there a config option so that the plugin doesn't override the default vim yank keybinds? A more granular way to customize the keybinds would also be nice.

**Comment by mikesmithgh** [comment]
Hey @musjj,

I have plans to add more detailed documentation and guides for configuring keymaps/options.

There are a couple things you can do at the moment.

Example disable all keymaps: https://github.com/mikesmithgh/kitty-scrollback.nvim/blob/main/lua/kitty-scrollback/configs/keymaps_disabled.lua
Example override keymaps: https://github.com/mikesmithgh/kitty-scrollback.nvim/blob/main/lua/kitty-scrollback/configs/keymaps_custom.lua
 - [&lt;NOP&gt;](https://neovim.io/doc/user/intro.html#%3CNop%3E) could also be used to disable certain keymaps (e.g., `lua vim.keymap.set({ 'n' }, '<Plug>(KsbYankLine)', '<NOP>', {})`)

If you run the command `:KittyScrollbackGenerateKittens!` it will display a list of kittens pointing to all of the example configs.

Those should allow you to reconfigure the default keymaps (https://github.com/mikesmithgh/kitty-scrollback.nvim/blob/main/lua/kitty-scrollback/keymaps.lua#L20).

Right now, yanks to the unnamed register are handled by an autocommand and not by a keymap. So that can't be configured, https://github.com/mikesmithgh/kitty-scrollback.nvim/blob/main/lua/kitty-scrollback/autocommands.lua#L165
- I could add an option to specify a register or nil to allow that to be configured or disabled. Is this something that you are interested in?

Appreciate the feedback 👍

**Comment by musjj** [comment]
Thanks, that's interesting, I didn't realize that the plugin uses a separate config file. Are there any plans to go with the conventional `require("kitty-scrollback").setup(...)` configuration method? That'd make configuration a lot easier.

> I could add an option to specify a register or nil to allow that to be configured or disabled. Is this something that you are interested in?

Yes, it would be nice if there's an option to configure this too!

**Comment by musjj** [comment]
Yes, that sounds pretty good! Maybe also have a special `default` config key, that when specified, will get invoked when no `--config` is provided? But I'm just bikeshedding here, either way would be fine.

**Comment by mikesmithgh** [comment]
Hey @musjj , I released adding configs to your setup function in `v2.0.0` let me know how this works for you 👍

**Comment by musjj** [comment]
Thank you!
