### ISSUE TITLE
v4.0.0 seems to regress performance

### ISSUE THREAD

**Issue by lazywei** [mikesmithgh/kitty-scrollback.nvim#180]
Hi, first of all, thanks for making this, it's been my daily driver for the past few months.

However, I notice after upgrading to 4.0.0, there seems to be a quite noticeable delay after hitting the `kitty_mod + h` and before the rendering is ready. I don't have a very accurate measuring for this and it's just subjective, but it seems the performance has regressed comparing to older version.

Another issue with v4.0.0 is it's trying to load the config even after setting the minimal config via `--clean --noplugin -n`, and this makes the opening speed worse, in additional to that, if my nvim config has something like this `os.getenv("OPENAI_API_KEY"),`, it will fail as well because it seems the scrollback can't read the ENVs defined in my zshrc or other shell config.

Is there a better way to mitigate this?

**Comment by mikesmithgh** [comment]
@lazywei 

> Hi, first of all, thanks for making this, it's been my daily driver for the past few months.

Thanks, that is awesome to hear! 😸 

>  I notice after upgrading to 4.0.0, there seems to be a quite noticeable delay after hitting the kitty_mod + h and before the rendering is ready. 

This make sense to me if you previously did not load you Neovim configuration. Now that is is loading it, there will be some delay depending on your configuration.

>  it's trying to load the config even after setting the minimal config via --clean --noplugin -n,

This shouldn't happen. It is either a bug or misconfig, could you share your configuration (kitty.conf) for this?


>  my nvim config has something like this os.getenv("OPENAI_API_KEY"),, it will fail as well because it seems the scrollback can't read the ENVs

> it seems the scrollback can't read the ENVs defined in my zshrc or other shell config.

This is a good point. Since it is opening nvim in an overlay window, those environment variables aren't copied over. I'll have to look into this to see if there is a way to copy that data. Kitty offers a `--copy-env` flag that I use (https://github.com/mikesmithgh/kitty-scrollback.nvim/blob/main/python/kitty_scrollback_nvim.py#L152), but at the point it is called the env already lost the information. 

If you just need a few environment variables in kitty-scrollback.nvim, then you can do that via the `--env` flag. It is not ideal, but something like this:
```
action_alias kitty_scrollback_nvim kitten /Users/mike/gitrepos/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py --env OPENAI_API_KEY=yourkey
```

**Comment by mikesmithgh** [comment]
> it's trying to load the config even after setting the minimal config via --clean --noplugin -n,

FYI I just fixed a spot in the README that was missing `--nvim-args` which may be why this didn't work for you. 

`--nvim-args --clean --noplugin -n` should work

**Comment by mikesmithgh** [comment]
> Oh that's great. Yeah I tried again now it seems `--nvim-args --clean --noplugin -n` solves the issue perfectly!

awesome

> Just out of curious - is the reason we change the default behavior cuz most people actually prefer their config to be loaded :-P?

Good question, I'm not sure actually what most people prefer 😂. The reason I switched it is because I list a lot of configurations options on the page. However, when it is `--clean --noplugin -n`, it doesn't load your config. So users were adding configs following the instructions and then not seeing them reflected. You could pass `--no-nvim-args` at the time, but this was also confusing so I just removed that flag and swapped the default behavior. So at least now people can configure it following the instructions and choose to opt out.

Thanks for the feedback.

**Comment by mikesmithgh** [comment]
Hey @lazywei I am closing this out. If you need any help feel free to reopen or create a new issue 👍
