### ISSUE TITLE
bug: paste window opens when the scrollback buffer is first entered

### ISSUE THREAD

**Issue by thisisrandy** [mikesmithgh/kitty-scrollback.nvim#273]
![pastewindow](https://github.com/user-attachments/assets/bf4ad06f-a7ac-4561-ad50-ef41e3daa2d3)

Why is the paste window open and in focus when nvim is first entered? It seems that if there's nothing there initially, it only forces the user to leave insert mode and quit the window pointlessly everytime before making actual use of the tool.

Have I somehow configured myself into a bad state, or is the the intended behavior? I've been unable to find any relevant settings thus far.

**Comment by mikesmithgh** [comment]
Hi @thisisrandy , this is not expected behavior. 

The paste window opens when the terminal buffer enters insert mode. kitty-scrollback.nvim loads the scrollback buffer contents into Neovim's terminal. Most likely, you have an autocommand that is triggering to insert when you enter a terminal buffer. Could you share you configuration?

**Comment by mikesmithgh** [comment]
You could do this if you want to keep that for your normal Neovim sessions but exclude for kitty-scrollback.nvim:

```lua
if vim.env.KITTY_SCROLLBACK_NVIM ~= 'true' then
  local term_insert = augroup("TermInsert")
  vim.api.nvim_create_autocmd("TermOpen", {
    group = term_insert,
    callback = function()
      vim.cmd.startinsert()
    end,
  })
end
```

> is it intentional for the paste window cursor to appear a line below the yanked text?

hmm this is how it is implemented, but I haven't thought too much about it to be honest. I may have did this since you can close the paste window and yank other text which appends to the window. 

> My most common use case is to search for and yank some text, so that's that one extra keystroke that I'd love to do without if possible.

could you describe what you do after you yank? do you typically edit in that paste window or just return back to the shell?


If you just want to copy the text to clipboard, you can do `<leader>` before yanking. It will copy to clipboard and exit kitty-scrollback.nvim/return to shell. There is also the option of pressing `<shift>-<enter>` which will send the selected text to the shell and then close kitty-scrollback.nvim.

**Comment by thisisrandy** [comment]
> I may have did this since you can close the paste window and yank other text which appends to the window.

You mean so there's a blank line between each chunk? I guess I can see that being useful if you're gathering a bunch of disparate bits from a chunk of output, but I rarely find myself wanting to do something like that.

> you can do `<leader>` before yanking. It will copy to clipboard and exit

Oh, neat. That's a definite time-saver. I will admit to not having read your docs thoroughly, but I see that now in the Features section.

> could you describe what you do after you yank? 

I just made the transition from `gnome-terminal` and `tmux` to `kitty` yesterday. If `tmux` has any "gather bits from the output and edit them in a paste buffer" functionality, I wasn't aware of it. My primary use cases, as such, were 1) Inspect w/o copying anything, simply using the `tmux` as a pager, and 2) Find something specific, often a file name or file name pattern, copy it, and then paste it somewhere into my next command with perhaps some modification directly in the process of constructing said command.

Anything where I feel like I'm going to significantly munge the output is going to disk, so the more complicated cases for terminal-only output never really come up.
