### ISSUE TITLE
feat: add support for neovim v0.9

### ISSUE THREAD

**Issue by mikesmithgh** [mikesmithgh/kitty-scrollback.nvim#58]
> [!IMPORTANT]\
> Please like or comment on this ticket if this is something you would like implemented (I'm trying to gauge interest)

`v0.9` is currently the stable version of Neovim.

There have been multiple discussions asking around why `v0.10` is required.

Depending on availability and the next stable release of Neovim, make kitty-scrollback.nvim compatible with `v0.9`

**Comment by mikesmithgh** [comment]
See https://github.com/mikesmithgh/kitty-scrollback.nvim/discussions/53

**Comment by mikesmithgh** [comment]
See https://github.com/mikesmithgh/kitty-scrollback.nvim/discussions/55

**Comment by Andrew15-5** [comment]
I don't think I mentioned this before, but I created https://github.com/smoka7/multicursors.nvim/issues/67 because in Neovim v0.10 the plugin breaks https://github.com/okuuva/auto-save.nvim and itself. So I can't edit in multiple places + auto-save just doesn't work anymore (after I start using multicursor), and I have to manually save every time. So I do experience some negative consequences of an unstable Neovim version. This is an example why kitty-scrollback.nvim plugin should support at least the latest stable version (0.9.4).

**Comment by jackielii** [comment]
FWIW, [vim.system](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/_system.lua) source is just one file, can we vendor it and import it base on version?

**Comment by mikesmithgh** [comment]
Thanks for the PR @jackielii! kitty-scrollback.nvim now supports neovim `v0.9`.

Thanks all who added discussions/upvoted. If anyone has any problems, feel free to open an issue. 🐱
